### ISSUE TITLE
Update Sentinel CLI to 0.3.2

### ISSUE THREAD

**Issue by trinityprivacy** [sentinel-official/cli-client#30]
Hi,

Could you please update this official repo and create the release v0.3.2 as per fork from freQnik?

https://github.com/freQniK/cli-client/releases/tag/v0.3.2

Otherwise users get confused and complain that sentinel cli does not work.

Thank you!

**Comment by freQniK** [comment]
Yeah, I couldn't create a new release on here. Tony will have to. Meanwhile, I will be adding v0.3.2 with the "inactive_pending" fix shortly.

**Comment by freQniK** [comment]
v0.3.2 with `inactive_pending` fix. Builds for OS X (intel, arm), Linux (x86), and Windows (x86)

https://github.com/freQniK/cli-client/releases/tag/v0.3.2

**Comment by trinityprivacy** [comment]
@bsrinivas8687 @ironman0x7b2 could you please update to 0.3.2? Consequently I will updated docs as well ad it now points to freQnik repo.

**Comment by trinityprivacy** [comment]
Could you enable @freQniK as contributor so he can push CLI 0.3.2?
